
function playerControls(player, worldObject, dt)
  local facingRight = 1
  local facingLeft = -1
  local isJumping = false
  local speed = 200
  worldObject.body:setLinearDamping(0.8)
  -- initJumpVelocity = math.sqrt(player.gravity*player.jump_height)
  -- initImpulse = worldObject.body:getMass()*initJumpVelocity

  if love.keyboard.isDown('right') then
    player.direction = facingRight
    worldObject.body:applyForce(speed, 0)
	elseif love.keyboard.isDown('left') then
    player.direction = facingLeft
    worldObject.body:applyForce(-speed, 0)
    worldObject.body:setLinearDamping(0.8)
  end
  if love.keyboard.isDown('space') then
    local x,y = worldObject.body:getLinearVelocity();
    if y > -5 and y < 5 then
      worldObject.body:applyLinearImpulse(0, player.jump_height)
    end
  end
end

-- if love.keyboard.isDown("right") then --press the right arrow key to push the ball to the right
--   objects.ball.body:applyForce(400, 0)
-- elseif love.keyboard.isDown("left") then --press the left arrow key to push the ball to the left
--   objects.ball.body:applyForce(-400, 0)
-- elseif love.keyboard.isDown("up") then --press the up arrow key to set the ball in the air
--   objects.ball.body:setPosition(650/2, 650/2)
--   objects.ball.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
-- end
